### ISSUE TITLE
Input textbox not working

### ISSUE THREAD

**Issue by nerogcy** [craftworkgames/MonoGame.Squid#1]
Input textbox not working. cant write any text in side textbox

**Comment by craftworkgames** [comment]
I'm not maintaining this project anymore. It was purely an experiment to see if I could get something working.

You're welcome to fork it and fix it up yourself. Alternately, there's also a port of [Nuclex](https://github.com/craftworkgames/MonoGame.Extended/tree/develop/Source/MonoGame.Extended/NuclexGui) and we're also working on a new GUI system in [MonoGame.Extended](https://github.com/craftworkgames/MonoGame.Extended).
